
name: Latest Discovery File Image Build

on:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches: ["beta", "master"]
  workflow_dispatch:

env:
  IMAGE_NAME: "tis-devops-api"
  DOCKER_USERNAME: "abhishek976772"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-asyncio
          pip install python-semantic-release

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin

      - name: Semantic Versioning (Python Semantic Release)
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git

      - name: Build and push Docker image
        if: steps.semantic-release.outputs.new_release_published == 'true'
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.semantic-release.outputs.new_release_version }} .
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.semantic-release.outputs.new_release_version }}
